//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodHub.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đã bị vô hiệu hóa..
        /// </summary>
        public static string ActiveUserBehavior_InActiveAccount {
            get {
                return ResourceManager.GetString("ActiveUserBehavior.InActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truy cập trái phép.
        /// </summary>
        public static string ActiveUserBehavior_Unauthorized {
            get {
                return ResourceManager.GetString("ActiveUserBehavior.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khu vực đã tồn tại..
        /// </summary>
        public static string Area_CodeExists {
            get {
                return ResourceManager.GetString("Area.CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khu vực là bắt buộc..
        /// </summary>
        public static string Area_CodeRequired {
            get {
                return ResourceManager.GetString("Area.CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực này đã ngừng hoạt động..
        /// </summary>
        public static string Area_DeactivateForbidden {
            get {
                return ResourceManager.GetString("Area.DeactivateForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền xóa khu vực này..
        /// </summary>
        public static string Area_DeleteForbidden {
            get {
                return ResourceManager.GetString("Area.DeleteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực là bắt buộc..
        /// </summary>
        public static string Area_NameRequired {
            get {
                return ResourceManager.GetString("Area.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy khu vực..
        /// </summary>
        public static string Area_NotFound {
            get {
                return ResourceManager.GetString("Area.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền cập nhật khu vực này..
        /// </summary>
        public static string Area_UpdateForbidden {
            get {
                return ResourceManager.GetString("Area.UpdateForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị tạm khóa do nhập sai quá nhiều lần. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_AccountBlocked {
            get {
                return ResourceManager.GetString("Auth.AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thất bại: Không thể gửi email thông báo. Vui lòng kiểm tra lại địa chỉ email..
        /// </summary>
        public static string Auth_AccountCreationEmailFailed {
            get {
                return ResourceManager.GetString("Auth.AccountCreationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hiện đang bị khóa hoặc chưa kích hoạt..
        /// </summary>
        public static string Auth_AccountInactive {
            get {
                return ResourceManager.GetString("Auth.AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không khớp..
        /// </summary>
        public static string Auth_ConfirmPasswordMismatch {
            get {
                return ResourceManager.GetString("Auth.ConfirmPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu không được để trống..
        /// </summary>
        public static string Auth_ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("Auth.ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string Auth_EmployeeCodeRequired {
            get {
                return ResourceManager.GetString("Auth.EmployeeCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ..
        /// </summary>
        public static string Auth_InvalidAction {
            get {
                return ResourceManager.GetString("Auth.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không chính xác..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string Auth_InvalidResetLink {
            get {
                return ResourceManager.GetString("Auth.InvalidResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string Auth_InvalidToken {
            get {
                return ResourceManager.GetString("Auth.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token chứa thông tin không hợp lệ..
        /// </summary>
        public static string Auth_InvalidTokenClaims {
            get {
                return ResourceManager.GetString("Auth.InvalidTokenClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được để trống..
        /// </summary>
        public static string Auth_NewPasswordRequired {
            get {
                return ResourceManager.GetString("Auth.NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        public static string Auth_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu email tồn tại trong hệ thống, bạn sẽ nhận được hướng dẫn đặt lại mật khẩu..
        /// </summary>
        public static string Auth_PasswordResetGenericMessage {
            get {
                return ResourceManager.GetString("Auth.PasswordResetGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lại mật khẩu thành công..
        /// </summary>
        public static string Auth_PasswordResetSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token đã hết hạn..
        /// </summary>
        public static string Auth_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không tồn tại..
        /// </summary>
        public static string Auth_RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token làm mới đã bị thu hồi..
        /// </summary>
        public static string Auth_RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhiều yêu cầu reset mật khẩu. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_ResetRequestLimit {
            get {
                return ResourceManager.GetString("Auth.ResetRequestLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không được để trống..
        /// </summary>
        public static string Auth_TokenRequired {
            get {
                return ResourceManager.GetString("Auth.TokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhiều lần thử sai. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_TooManyAttempts {
            get {
                return ResourceManager.GetString("Auth.TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng chưa đăng nhập..
        /// </summary>
        public static string Auth_UserNotLoggedIn {
            get {
                return ResourceManager.GetString("Auth.UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác định Manager thực hiện thao tác.
        /// </summary>
        public static string CannotIdentifyManager {
            get {
                return ResourceManager.GetString("CannotIdentifyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chuyển sang vai trò Quản lý.
        /// </summary>
        public static string CannotPromoteToManager {
            get {
                return ResourceManager.GetString("CannotPromoteToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể vô hiệu hóa danh mục có món đang hoạt động..
        /// </summary>
        public static string Category_CannotDeactivateWithActiveItems {
            get {
                return ResourceManager.GetString("Category.CannotDeactivateWithActiveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa danh mục đang hoạt động..
        /// </summary>
        public static string Category_CannotDeleteActiveCategory {
            get {
                return ResourceManager.GetString("Category.CannotDeleteActiveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục không được để trống..
        /// </summary>
        public static string Category_NameRequired {
            get {
                return ResourceManager.GetString("Category.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại danh mục không hợp lệ..
        /// </summary>
        public static string Category_TypeInvalid {
            get {
                return ResourceManager.GetString("Category.TypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tệp thất bại..
        /// </summary>
        public static string Common_DeleteFailed {
            get {
                return ResourceManager.GetString("Common.DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tệp thành công..
        /// </summary>
        public static string Common_DeleteSuccess {
            get {
                return ResourceManager.GetString("Common.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh không khớp..
        /// </summary>
        public static string Common_IdMismatch {
            get {
                return ResourceManager.GetString("Common.IdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã định danh là bắt buộc..
        /// </summary>
        public static string Common_IdRequired {
            get {
                return ResourceManager.GetString("Common.IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống nội bộ..
        /// </summary>
        public static string Common_InternalServerError {
            get {
                return ResourceManager.GetString("Common.InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng cung cấp tệp tin..
        /// </summary>
        public static string Common_NoFileProvided {
            get {
                return ResourceManager.GetString("Common.NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên..
        /// </summary>
        public static string Common_NotFound {
            get {
                return ResourceManager.GetString("Common.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải tệp lên thành công..
        /// </summary>
        public static string Common_UploadSuccess {
            get {
                return ResourceManager.GetString("Common.UploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        public static string Common_ValidationFailed {
            get {
                return ResourceManager.GetString("Common.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có xung đột dữ liệu trong hệ thống. Vui lòng thử lại sau vài giây..
        /// </summary>
        public static string DatabaseConflict {
            get {
                return ResourceManager.GetString("DatabaseConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cập nhật dữ liệu. Vui lòng thử lại..
        /// </summary>
        public static string DatabaseUpdateError {
            get {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật thông tin cho nhân viên đang ngừng hoạt động..
        /// </summary>
        public static string Employee_CannotUpdateInactive {
            get {
                return ResourceManager.GetString("Employee.CannotUpdateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không đúng định dạng..
        /// </summary>
        public static string Employee_CodeInvalidFormat {
            get {
                return ResourceManager.GetString("Employee.CodeInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên này hiện không hoạt động..
        /// </summary>
        public static string EmployeeNotActive {
            get {
                return ResourceManager.GetString("EmployeeNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user identity is missing or invalid..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy danh mục với ID: {0}.
        /// </summary>
        public static string MenuItem_CategoryNotFound {
            get {
                return ResourceManager.GetString("MenuItem.CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục không được để trống..
        /// </summary>
        public static string MenuItem_CategoryRequired {
            get {
                return ResourceManager.GetString("MenuItem.CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món &apos;{0}&apos; đã tồn tại.
        /// </summary>
        public static string MenuItem_CodeExists {
            get {
                return ResourceManager.GetString("MenuItem.CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn không được để trống..
        /// </summary>
        public static string MenuItem_CodeRequired {
            get {
                return ResourceManager.GetString("MenuItem.CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn không được quá 50 ký tự..
        /// </summary>
        public static string MenuItem_CodeTooLong {
            get {
                return ResourceManager.GetString("MenuItem.CodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian chờ phải lớn hơn 0..
        /// </summary>
        public static string MenuItem_ExpectedTimeInvalid {
            get {
                return ResourceManager.GetString("MenuItem.ExpectedTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh không được để trống..
        /// </summary>
        public static string MenuItem_ImageRequired {
            get {
                return ResourceManager.GetString("MenuItem.ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn 0..
        /// </summary>
        public static string MenuItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("MenuItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món ăn không được để trống..
        /// </summary>
        public static string MenuItem_NameRequired {
            get {
                return ResourceManager.GetString("MenuItem.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món ăn không được quá 150 ký tự..
        /// </summary>
        public static string MenuItem_NameTooLong {
            get {
                return ResourceManager.GetString("MenuItem.NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy món ăn với ID: {0}.
        /// </summary>
        public static string MenuItem_NotFound {
            get {
                return ResourceManager.GetString("MenuItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món đã hết: .
        /// </summary>
        public static string MenuItem_OutOfStock {
            get {
                return ResourceManager.GetString("MenuItem.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán phải lớn hơn 0..
        /// </summary>
        public static string MenuItem_PriceInvalid {
            get {
                return ResourceManager.GetString("MenuItem.PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station không hợp lệ..
        /// </summary>
        public static string MenuItem_StationInvalid {
            get {
                return ResourceManager.GetString("MenuItem.StationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền cập nhật giá vốn của món ăn..
        /// </summary>
        public static string MenuItem_UpdateCostForbidden {
            get {
                return ResourceManager.GetString("MenuItem.UpdateCostForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền cập nhật trạng thái tồn kho..
        /// </summary>
        public static string MenuItem_UpdateStockForbidden {
            get {
                return ResourceManager.GetString("MenuItem.UpdateStockForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể reset password cho tài khoản đang hoạt động.
        /// </summary>
        public static string OnlyActiveEmployeeCanReset {
            get {
                return ResourceManager.GetString("OnlyActiveEmployeeCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ Manager mới có quyền reset password.
        /// </summary>
        public static string OnlyManagerCanReset {
            get {
                return ResourceManager.GetString("OnlyManagerCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác bị hủy do timeout. Vui lòng thử lại..
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa nhóm tùy chọn còn chứa tùy chọn..
        /// </summary>
        public static string OptionGroup_CannotDeleteWithOptions {
            get {
                return ResourceManager.GetString("OptionGroup.CannotDeleteWithOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tùy chọn không thể có cả Min và Max cùng lúc..
        /// </summary>
        public static string OptionGroup_CannotHaveBothMinAndMax {
            get {
                return ResourceManager.GetString("OptionGroup.CannotHaveBothMinAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món ăn không được để trống..
        /// </summary>
        public static string OptionGroup_MenuItemIdRequired {
            get {
                return ResourceManager.GetString("OptionGroup.MenuItemIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm tùy chọn không được để trống..
        /// </summary>
        public static string OptionGroup_NameRequired {
            get {
                return ResourceManager.GetString("OptionGroup.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhóm lựa chọn này.
        /// </summary>
        public static string OptionGroup_NotFound {
            get {
                return ResourceManager.GetString("OptionGroup.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tùy chọn không được để trống..
        /// </summary>
        public static string OptionGroup_Required {
            get {
                return ResourceManager.GetString("OptionGroup.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá thêm phải lớn hơn hoặc bằng 0..
        /// </summary>
        public static string OptionItem_ExtraPriceInvalid {
            get {
                return ResourceManager.GetString("OptionItem.ExtraPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá thêm phải lớn hơn hoặc bằng 0..
        /// </summary>
        public static string OptionItem_InvalidExtraPrice {
            get {
                return ResourceManager.GetString("OptionItem.InvalidExtraPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tùy chọn không được để trống..
        /// </summary>
        public static string OptionItem_LabelRequired {
            get {
                return ResourceManager.GetString("OptionItem.LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy lựa chọn này..
        /// </summary>
        public static string OptionItem_NotFound {
            get {
                return ResourceManager.GetString("OptionItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ.
        /// </summary>
        public static string Order_InvalidAction {
            get {
                return ResourceManager.GetString("Order.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ với trạng thái.
        /// </summary>
        public static string Order_InvalidActionWithStatus {
            get {
                return ResourceManager.GetString("Order.InvalidActionWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không hợp lệ.
        /// </summary>
        public static string Order_InvalidQuantity {
            get {
                return ResourceManager.GetString("Order.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng không thể huỷ ở trạng thái hiện tại..
        /// </summary>
        public static string Order_InvalidStatusForCancel {
            get {
                return ResourceManager.GetString("Order.InvalidStatusForCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đơn không hợp lệ..
        /// </summary>
        public static string Order_InvalidType {
            get {
                return ResourceManager.GetString("Order.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đang trống..
        /// </summary>
        public static string Order_MustHaveItem {
            get {
                return ResourceManager.GetString("Order.MustHaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn..
        /// </summary>
        public static string Order_NotFound {
            get {
                return ResourceManager.GetString("Order.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng chưa sẵn sàng để hoàn tất. Vui lòng kiểm tra các món còn đang xử lý..
        /// </summary>
        public static string Order_OrderNotReadyForCompletion {
            get {
                return ResourceManager.GetString("Order.OrderNotReadyForCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lý do cho thao tác này..
        /// </summary>
        public static string Order_ReasonRequired {
            get {
                return ResourceManager.GetString("Order.ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn bàn cho đơn dùng tại nhà hàng.
        /// </summary>
        public static string Order_SelectTable {
            get {
                return ResourceManager.GetString("Order.SelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn này đang có khách. Vui lòng chọn bàn khác..
        /// </summary>
        public static string Order_TableAlreadyOccupied {
            get {
                return ResourceManager.GetString("Order.TableAlreadyOccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số tiền đang có sự chênh lệch.
        /// </summary>
        public static string Order_WrongTotalAmount {
            get {
                return ResourceManager.GetString("Order.WrongTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có ít nhất 1 món để gửi bếp.
        /// </summary>
        public static string OrderItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("OrderItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món không thể huỷ ở trạng thái hiện tại..
        /// </summary>
        public static string OrderItem_InvalidStatusForCancel {
            get {
                return ResourceManager.GetString("OrderItem.InvalidStatusForCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món phải đang nấu để chuyển sang trạng thái Sẵn sàng..
        /// </summary>
        public static string OrderItem_MustBeCookingToReady {
            get {
                return ResourceManager.GetString("OrderItem.MustBeCookingToReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món phải đang nấu để từ chối..
        /// </summary>
        public static string OrderItem_MustBeCookingToReject {
            get {
                return ResourceManager.GetString("OrderItem.MustBeCookingToReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món phải đang ở trạng thái Chuẩn bị để bắt đầu nấu..
        /// </summary>
        public static string OrderItem_MustBePreparingToStartCooking {
            get {
                return ResourceManager.GetString("OrderItem.MustBePreparingToStartCooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món phải bị từ chối để hoàn trả..
        /// </summary>
        public static string OrderItem_MustBeRejectedToReturn {
            get {
                return ResourceManager.GetString("OrderItem.MustBeRejectedToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy món trong đơn hàng..
        /// </summary>
        public static string OrderItem_NotFound {
            get {
                return ResourceManager.GetString("OrderItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lý do từ chối món ăn..
        /// </summary>
        public static string OrderItem_RejectionReasonIsRequired {
            get {
                return ResourceManager.GetString("OrderItem.RejectionReasonIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập lý do từ chối món ăn..
        /// </summary>
        public static string OrderItem_RejectionReasonRequired {
            get {
                return ResourceManager.GetString("OrderItem.RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không khớp..
        /// </summary>
        public static string Password_ConfirmationMismatch {
            get {
                return ResourceManager.GetString("Password.ConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không chính xác..
        /// </summary>
        public static string Password_IncorrectCurrent {
            get {
                return ResourceManager.GetString("Password.IncorrectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 8 ký tự.
        /// </summary>
        public static string Password_MinLength {
            get {
                return ResourceManager.GetString("Password.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải khác mật khẩu hiện tại..
        /// </summary>
        public static string Password_MustBeDifferent {
            get {
                return ResourceManager.GetString("Password.MustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 số.
        /// </summary>
        public static string Password_RequireDigit {
            get {
                return ResourceManager.GetString("Password.RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 chữ thường.
        /// </summary>
        public static string Password_RequireLowercase {
            get {
                return ResourceManager.GetString("Password.RequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 ký tự đặc biệt.
        /// </summary>
        public static string Password_RequireSpecial {
            get {
                return ResourceManager.GetString("Password.RequireSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 chữ hoa.
        /// </summary>
        public static string Password_RequireUppercase {
            get {
                return ResourceManager.GetString("Password.RequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng..
        /// </summary>
        public static string Profile_EmailExists {
            get {
                return ResourceManager.GetString("Profile.EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng bởi người khác..
        /// </summary>
        public static string Profile_PhoneExists {
            get {
                return ResourceManager.GetString("Profile.PhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập đã được sử dụng bởi người khác..
        /// </summary>
        public static string Profile_UsernameExists {
            get {
                return ResourceManager.GetString("Profile.UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId không được để trống.
        /// </summary>
        public static string ResetPassword_EmployeeIdRequired {
            get {
                return ResourceManager.GetString("ResetPassword.EmployeeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset không được quá 500 ký tự.
        /// </summary>
        public static string ResetPassword_ReasonMaxLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset phải có ít nhất 10 ký tự.
        /// </summary>
        public static string ResetPassword_ReasonMinLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset password là bắt buộc.
        /// </summary>
        public static string ResetPassword_ReasonRequired {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có email để thông báo trạng thái..
        /// </summary>
        public static string ResetPassword_StatusNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.StatusNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset mật khẩu thành công. Không có email để thông báo..
        /// </summary>
        public static string ResetPassword_SuccessNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset mật khẩu thành công. Email thông báo đã được gửi..
        /// </summary>
        public static string ResetPassword_SuccessWithEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa set menu còn chứa món..
        /// </summary>
        public static string SetMenu_CannotDeleteWithItems {
            get {
                return ResourceManager.GetString("SetMenu.CannotDeleteWithItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã set menu đã tồn tại..
        /// </summary>
        public static string SetMenu_CodeExists {
            get {
                return ResourceManager.GetString("SetMenu.CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã set menu không được để trống..
        /// </summary>
        public static string SetMenu_CodeRequired {
            get {
                return ResourceManager.GetString("SetMenu.CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền xóa set menu này..
        /// </summary>
        public static string SetMenu_DeleteForbidden {
            get {
                return ResourceManager.GetString("SetMenu.DeleteForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set menu phải có ít nhất 1 món..
        /// </summary>
        public static string SetMenu_ItemsRequired {
            get {
                return ResourceManager.GetString("SetMenu.ItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên set menu không được để trống..
        /// </summary>
        public static string SetMenu_NameRequired {
            get {
                return ResourceManager.GetString("SetMenu.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy set menu..
        /// </summary>
        public static string SetMenu_NotFound {
            get {
                return ResourceManager.GetString("SetMenu.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán phải lớn hơn 0..
        /// </summary>
        public static string SetMenu_PriceInvalid {
            get {
                return ResourceManager.GetString("SetMenu.PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền cập nhật set menu này..
        /// </summary>
        public static string SetMenu_UpdateForbidden {
            get {
                return ResourceManager.GetString("SetMenu.UpdateForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện thao tác này..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
