//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodHub.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài kho?n b? t?m khóa do nh?p sai quá nhi?u l?n. Vui lòng th? l?i sau..
        /// </summary>
        public static string Auth_AccountBlocked {
            get {
                return ResourceManager.GetString("Auth.AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T?o tài kho?n th?t b?i: Không th? g?i email thông báo. Vui lòng ki?m tra l?i d?a ch? email..
        /// </summary>
        public static string Auth_AccountCreationEmailFailed {
            get {
                return ResourceManager.GetString("Auth.AccountCreationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài kho?n hi?n dang b? khóa ho?c chua kích ho?t..
        /// </summary>
        public static string Auth_AccountInactive {
            get {
                return ResourceManager.GetString("Auth.AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không h?p l?..
        /// </summary>
        public static string Auth_InvalidAction {
            get {
                return ResourceManager.GetString("Auth.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ho?c m?t kh?u không chính xác..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link không h?p l? ho?c dã h?t h?n..
        /// </summary>
        public static string Auth_InvalidResetLink {
            get {
                return ResourceManager.GetString("Auth.InvalidResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không h?p l? ho?c dã h?t h?n..
        /// </summary>
        public static string Auth_InvalidToken {
            get {
                return ResourceManager.GetString("Auth.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token dã h?t h?n..
        /// </summary>
        public static string Auth_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không t?n t?i..
        /// </summary>
        public static string Auth_RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token làm m?i dã b? thu h?i..
        /// </summary>
        public static string Auth_RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhi?u yêu c?u reset m?t kh?u. Vui lòng th? l?i sau..
        /// </summary>
        public static string Auth_ResetRequestLimit {
            get {
                return ResourceManager.GetString("Auth.ResetRequestLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhi?u l?n th? sai. Vui lòng th? l?i sau..
        /// </summary>
        public static string Auth_TooManyAttempts {
            get {
                return ResourceManager.GetString("Auth.TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngu?i dùng chua dang nh?p..
        /// </summary>
        public static string Auth_UserNotLoggedIn {
            get {
                return ResourceManager.GetString("Auth.UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không th? xác d?nh Manager th?c hi?n thao tác.
        /// </summary>
        public static string CannotIdentifyManager {
            get {
                return ResourceManager.GetString("CannotIdentifyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh m?c không du?c d? tr?ng..
        /// </summary>
        public static string Category_NameRequired {
            get {
                return ResourceManager.GetString("Category.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo?i danh m?c không h?p l?..
        /// </summary>
        public static string Category_TypeInvalid {
            get {
                return ResourceManager.GetString("Category.TypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có xung d?t d? li?u trong h? th?ng. Vui lòng th? l?i sau vài giây..
        /// </summary>
        public static string DatabaseConflict {
            get {
                return ResourceManager.GetString("DatabaseConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có l?i x?y ra khi c?p nh?t d? li?u. Vui lòng th? l?i..
        /// </summary>
        public static string DatabaseUpdateError {
            get {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không th? c?p nh?t thông tin cho nhân viên dang ng?ng ho?t d?ng..
        /// </summary>
        public static string Employee_CannotUpdateInactive {
            get {
                return ResourceManager.GetString("Employee.CannotUpdateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user identity is missing or invalid..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm th?y danh m?c v?i ID: {0}.
        /// </summary>
        public static string MenuItem_CategoryNotFound {
            get {
                return ResourceManager.GetString("MenuItem.CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh m?c không du?c d? tr?ng..
        /// </summary>
        public static string MenuItem_CategoryRequired {
            get {
                return ResourceManager.GetString("MenuItem.CategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món &apos;{0}&apos; dã t?n t?i.
        /// </summary>
        public static string MenuItem_CodeExists {
            get {
                return ResourceManager.GetString("MenuItem.CodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món an không du?c d? tr?ng..
        /// </summary>
        public static string MenuItem_CodeRequired {
            get {
                return ResourceManager.GetString("MenuItem.CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món an không du?c quá 50 ký t?..
        /// </summary>
        public static string MenuItem_CodeTooLong {
            get {
                return ResourceManager.GetString("MenuItem.CodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th?i gian ch? ph?i l?n hon 0..
        /// </summary>
        public static string MenuItem_ExpectedTimeInvalid {
            get {
                return ResourceManager.GetString("MenuItem.ExpectedTimeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ?nh không du?c d? tr?ng..
        /// </summary>
        public static string MenuItem_ImageRequired {
            get {
                return ResourceManager.GetString("MenuItem.ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S? lu?ng ph?i l?n hon 0..
        /// </summary>
        public static string MenuItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("MenuItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món an không du?c d? tr?ng..
        /// </summary>
        public static string MenuItem_NameRequired {
            get {
                return ResourceManager.GetString("MenuItem.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món an không du?c quá 150 ký t?..
        /// </summary>
        public static string MenuItem_NameTooLong {
            get {
                return ResourceManager.GetString("MenuItem.NameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm th?y món an trong menu..
        /// </summary>
        public static string MenuItem_NotFound {
            get {
                return ResourceManager.GetString("MenuItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món dã h?t: .
        /// </summary>
        public static string MenuItem_OutOfStock {
            get {
                return ResourceManager.GetString("MenuItem.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán ph?i l?n hon 0..
        /// </summary>
        public static string MenuItem_PriceInvalid {
            get {
                return ResourceManager.GetString("MenuItem.PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station không h?p l?..
        /// </summary>
        public static string MenuItem_StationInvalid {
            get {
                return ResourceManager.GetString("MenuItem.StationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch? có th? reset password cho tài kho?n dang ho?t d?ng.
        /// </summary>
        public static string OnlyActiveEmployeeCanReset {
            get {
                return ResourceManager.GetString("OnlyActiveEmployeeCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ch? Manager m?i có quy?n reset password.
        /// </summary>
        public static string OnlyManagerCanReset {
            get {
                return ResourceManager.GetString("OnlyManagerCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác b? h?y do timeout. Vui lòng th? l?i..
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món an không du?c d? tr?ng..
        /// </summary>
        public static string OptionGroup_MenuItemIdRequired {
            get {
                return ResourceManager.GetString("OptionGroup.MenuItemIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm tùy ch?n không du?c d? tr?ng..
        /// </summary>
        public static string OptionGroup_NameRequired {
            get {
                return ResourceManager.GetString("OptionGroup.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm th?y nhóm l?a ch?n này.
        /// </summary>
        public static string OptionGroup_NotFound {
            get {
                return ResourceManager.GetString("OptionGroup.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm tùy ch?n không du?c d? tr?ng..
        /// </summary>
        public static string OptionGroup_Required {
            get {
                return ResourceManager.GetString("OptionGroup.Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá thêm ph?i l?n hon ho?c b?ng 0..
        /// </summary>
        public static string OptionItem_ExtraPriceInvalid {
            get {
                return ResourceManager.GetString("OptionItem.ExtraPriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tùy ch?n không du?c d? tr?ng..
        /// </summary>
        public static string OptionItem_LabelRequired {
            get {
                return ResourceManager.GetString("OptionItem.LabelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm th?y l?a ch?n này..
        /// </summary>
        public static string OptionItem_NotFound {
            get {
                return ResourceManager.GetString("OptionItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không h?p l?.
        /// </summary>
        public static string Order_InvalidAction {
            get {
                return ResourceManager.GetString("Order.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không h?p l? v?i tr?ng thái.
        /// </summary>
        public static string Order_InvalidActionWithStatus {
            get {
                return ResourceManager.GetString("Order.InvalidActionWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S? lu?ng không h?p l?.
        /// </summary>
        public static string Order_InvalidQuantity {
            get {
                return ResourceManager.GetString("Order.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo?i don không h?p l?..
        /// </summary>
        public static string Order_InvalidType {
            get {
                return ResourceManager.GetString("Order.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ðon hàng dang tr?ng..
        /// </summary>
        public static string Order_MustHaveItem {
            get {
                return ResourceManager.GetString("Order.MustHaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm th?y don..
        /// </summary>
        public static string Order_NotFound {
            get {
                return ResourceManager.GetString("Order.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng ch?n bàn cho don dùng t?i nhà hàng.
        /// </summary>
        public static string Order_SelectTable {
            get {
                return ResourceManager.GetString("Order.SelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T?ng s? ti?n dang có s? chênh l?ch.
        /// </summary>
        public static string Order_WrongTotalAmount {
            get {
                return ResourceManager.GetString("Order.WrongTotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ph?i có ít nh?t 1 món d? g?i b?p.
        /// </summary>
        public static string OrderItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("OrderItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u xác nh?n không kh?p..
        /// </summary>
        public static string Password_ConfirmationMismatch {
            get {
                return ResourceManager.GetString("Password.ConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u hi?n t?i không chính xác..
        /// </summary>
        public static string Password_IncorrectCurrent {
            get {
                return ResourceManager.GetString("Password.IncorrectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u ph?i có ít nh?t 8 ký t?.
        /// </summary>
        public static string Password_MinLength {
            get {
                return ResourceManager.GetString("Password.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u m?i ph?i khác m?t kh?u hi?n t?i..
        /// </summary>
        public static string Password_MustBeDifferent {
            get {
                return ResourceManager.GetString("Password.MustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u ph?i có ít nh?t 1 s?.
        /// </summary>
        public static string Password_RequireDigit {
            get {
                return ResourceManager.GetString("Password.RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u ph?i có ít nh?t 1 ch? thu?ng.
        /// </summary>
        public static string Password_RequireLowercase {
            get {
                return ResourceManager.GetString("Password.RequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u ph?i có ít nh?t 1 ký t? d?c bi?t.
        /// </summary>
        public static string Password_RequireSpecial {
            get {
                return ResourceManager.GetString("Password.RequireSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M?t kh?u ph?i có ít nh?t 1 ch? hoa.
        /// </summary>
        public static string Password_RequireUppercase {
            get {
                return ResourceManager.GetString("Password.RequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email dã du?c s? d?ng b?i ngu?i khác..
        /// </summary>
        public static string Profile_EmailExists {
            get {
                return ResourceManager.GetString("Profile.EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S? di?n tho?i dã du?c s? d?ng b?i ngu?i khác..
        /// </summary>
        public static string Profile_PhoneExists {
            get {
                return ResourceManager.GetString("Profile.PhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId không du?c d? tr?ng.
        /// </summary>
        public static string ResetPassword_EmployeeIdRequired {
            get {
                return ResourceManager.GetString("ResetPassword.EmployeeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset không du?c quá 500 ký t?.
        /// </summary>
        public static string ResetPassword_ReasonMaxLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset ph?i có ít nh?t 10 ký t?.
        /// </summary>
        public static string ResetPassword_ReasonMinLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset password là b?t bu?c.
        /// </summary>
        public static string ResetPassword_ReasonRequired {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã set menu không du?c d? tr?ng..
        /// </summary>
        public static string SetMenu_CodeRequired {
            get {
                return ResourceManager.GetString("SetMenu.CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set menu ph?i có ít nh?t 1 món..
        /// </summary>
        public static string SetMenu_ItemsRequired {
            get {
                return ResourceManager.GetString("SetMenu.ItemsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên set menu không du?c d? tr?ng..
        /// </summary>
        public static string SetMenu_NameRequired {
            get {
                return ResourceManager.GetString("SetMenu.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán ph?i l?n hon 0..
        /// </summary>
        public static string SetMenu_PriceInvalid {
            get {
                return ResourceManager.GetString("SetMenu.PriceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B?n không có quy?n th?c hi?n thao tác này..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
