//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodHub.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho nhân viên. Mã: {0}, Mật khẩu: {1}.
        /// </summary>
        public static string AccountCreatedButEmailFailed {
            get {
                return ResourceManager.GetString("AccountCreatedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công.
        /// </summary>
        public static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        public static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth.LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        public static string Auth_LogoutSuccess {
            get {
                return ResourceManager.GetString("Auth.LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công..
        /// </summary>
        public static string Auth_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu tài khoản hợp lệ, hệ thống sẽ gửi link reset mật khẩu qua email..
        /// </summary>
        public static string Auth_PasswordResetGenericMessage {
            get {
                return ResourceManager.GetString("Auth.PasswordResetGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link reset mật khẩu đã được gửi vào email của bạn..
        /// </summary>
        public static string Auth_PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("Auth.PasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công..
        /// </summary>
        public static string Auth_PasswordResetSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định được người thực hiện thao tác..
        /// </summary>
        public static string CannotIdentifyUser {
            get {
                return ResourceManager.GetString("CannotIdentifyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể cho người khác thành quản lí.
        /// </summary>
        public static string CannotPromoteToManager {
            get {
                return ResourceManager.GetString("CannotPromoteToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên hiện tại không còn hoạt động..
        /// </summary>
        public static string EmployeeNotActive {
            get {
                return ResourceManager.GetString("EmployeeNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhân viên với mã và role hiện tại..
        /// </summary>
        public static string EmployeeNotFound {
            get {
                return ResourceManager.GetString("EmployeeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí mới phải khác vị trí hiện tại.
        /// </summary>
        public static string NewRoleMustBeDifferent {
            get {
                return ResourceManager.GetString("NewRoleMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công..
        /// </summary>
        public static string Profile_UpdateSuccess {
            get {
                return ResourceManager.GetString("Profile.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho nhân viên. Mật khẩu mới: {0}.
        /// </summary>
        public static string ResetPassword_SuccessNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công. Email thông báo đã được gửi tới {0}.
        /// </summary>
        public static string ResetPassword_SuccessWithEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email thông báo không được gửi. Vui lòng thông báo trực tiếp cho nhân viên..
        /// </summary>
        public static string ResetStatusNoEmail {
            get {
                return ResourceManager.GetString("ResetStatusNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho nhân viên về mã nhân viên mới: {0}.
        /// </summary>
        public static string RoleChangedButEmailFailed {
            get {
                return ResourceManager.GetString("RoleChangedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công.
        /// </summary>
        public static string RoleChangedSuccessfully {
            get {
                return ResourceManager.GetString("RoleChangedSuccessfully", resourceCulture);
            }
        }
    }
}
