using FoodHub.Application.Common.Models;
using MediatR;

namespace FoodHub.Application.Features.Branding.Settings.Commands.UpdateBrandingSettings
{
    public record UpdateBrandingSettingsCommand(
        string RestaurantName,
        string BranchName,
        string Address,
        string Phone,
        string Currency,
        string DateFormat,
        string Timezone,
        string Language,
        string BillTitle,
        string BillFooter,
        string KdsTitle,
        string AppTitle,
        string LogoUrl,
        string LegalBusinessName,
        string BrandName,
        string TaxCode,
        string BusinessRegistrationNumber,
        string BranchCode,
        string RestaurantCode,
        string Hotline,
        string Email,
        string Website,
        string Facebook,
        string ZaloOa,
        string Instagram,
        string Country,
        string ProvinceCity,
        string District,
        string Ward,
        string StreetAddress,
        string PostalCode,
        string GoogleMapUrl,
        string CoverImageUrl,
        string QrPaymentImageUrl,
        string FaviconUrl,
        decimal VatPercentage,
        string TimeFormat,
        string OpeningTime,
        string ClosingTime,
        string WorkingDays,
        bool EnableOrdering,
        bool EnableDelivery,
        bool EnableTakeAway,
        bool EnableReservation
    ) : IRequest<Result<UpdateBrandingSettingsResponse>>;
}
