//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Application.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodHub.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Có xung đột dữ liệu trong hệ thống. Vui lòng thử lại sau vài giây..
        /// </summary>
        public static string DatabaseConflict
        {
            get
            {
                return ResourceManager.GetString("DatabaseConflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cập nhật dữ liệu. Vui lòng thử lại..
        /// </summary>
        public static string DatabaseUpdateError
        {
            get
            {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current user identity is missing or invalid..
        /// </summary>
        public static string InvalidUserId
        {
            get
            {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thao tác bị hủy do timeout. Vui lòng thử lại..
        /// </summary>
        public static string OperationCancelled
        {
            get
            {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện thao tác này..
        /// </summary>
        public static string Unauthorized
        {
            get
            {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
