//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodHub.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodHub.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản bị tạm khóa do nhập sai quá nhiều lần. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_AccountBlocked {
            get {
                return ResourceManager.GetString("Auth.AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo tài khoản thất bại: Không thể gửi email thông báo. Vui lòng kiểm tra lại địa chỉ email..
        /// </summary>
        public static string Auth_AccountCreationEmailFailed {
            get {
                return ResourceManager.GetString("Auth.AccountCreationEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hiện đang bị khóa hoặc chưa kích hoạt..
        /// </summary>
        public static string Auth_AccountInactive {
            get {
                return ResourceManager.GetString("Auth.AccountInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ..
        /// </summary>
        public static string Auth_InvalidAction {
            get {
                return ResourceManager.GetString("Auth.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không chính xác..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string Auth_InvalidResetLink {
            get {
                return ResourceManager.GetString("Auth.InvalidResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ hoặc đã hết hạn..
        /// </summary>
        public static string Auth_InvalidToken {
            get {
                return ResourceManager.GetString("Auth.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token đã hết hạn..
        /// </summary>
        public static string Auth_RefreshTokenExpired {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token không tồn tại..
        /// </summary>
        public static string Auth_RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token làm mới đã bị thu hồi..
        /// </summary>
        public static string Auth_RefreshTokenRevoked {
            get {
                return ResourceManager.GetString("Auth.RefreshTokenRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhiều yêu cầu reset mật khẩu. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_ResetRequestLimit {
            get {
                return ResourceManager.GetString("Auth.ResetRequestLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá nhiều lần thử sai. Vui lòng thử lại sau..
        /// </summary>
        public static string Auth_TooManyAttempts {
            get {
                return ResourceManager.GetString("Auth.TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng chưa đăng nhập..
        /// </summary>
        public static string Auth_UserNotLoggedIn {
            get {
                return ResourceManager.GetString("Auth.UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác định Manager thực hiện thao tác.
        /// </summary>
        public static string CannotIdentifyManager {
            get {
                return ResourceManager.GetString("CannotIdentifyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có xung đột dữ liệu trong hệ thống. Vui lòng thử lại sau vài giây..
        /// </summary>
        public static string DatabaseConflict {
            get {
                return ResourceManager.GetString("DatabaseConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cập nhật dữ liệu. Vui lòng thử lại..
        /// </summary>
        public static string DatabaseUpdateError {
            get {
                return ResourceManager.GetString("DatabaseUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật thông tin cho nhân viên đang ngừng hoạt động..
        /// </summary>
        public static string Employee_CannotUpdateInactive {
            get {
                return ResourceManager.GetString("Employee.CannotUpdateInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user identity is missing or invalid..
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn 0..
        /// </summary>
        public static string MenuItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("MenuItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy món ăn trong menu..
        /// </summary>
        public static string MenuItem_NotFound {
            get {
                return ResourceManager.GetString("MenuItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món đã hết: .
        /// </summary>
        public static string MenuItem_OutOfStock {
            get {
                return ResourceManager.GetString("MenuItem.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ có thể reset password cho tài khoản đang hoạt động.
        /// </summary>
        public static string OnlyActiveEmployeeCanReset {
            get {
                return ResourceManager.GetString("OnlyActiveEmployeeCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ Manager mới có quyền reset password.
        /// </summary>
        public static string OnlyManagerCanReset {
            get {
                return ResourceManager.GetString("OnlyManagerCanReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác bị hủy do timeout. Vui lòng thử lại..
        /// </summary>
        public static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy nhóm lựa chọn này.
        /// </summary>
        public static string OptionGroup_NotFound {
            get {
                return ResourceManager.GetString("OptionGroup.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy lựa chọn này..
        /// </summary>
        public static string OptionItem_NotFound {
            get {
                return ResourceManager.GetString("OptionItem.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ.
        /// </summary>
        public static string Order_InvalidAction {
            get {
                return ResourceManager.GetString("Order.InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thao tác không hợp lệ với trạng thái.
        /// </summary>
        public static string Order_InvalidActionWithStatus {
            get {
                return ResourceManager.GetString("Order.InvalidActionWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không hợp lệ.
        /// </summary>
        public static string Order_InvalidQuantity {
            get {
                return ResourceManager.GetString("Order.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại đơn không hợp lệ..
        /// </summary>
        public static string Order_InvalidType {
            get {
                return ResourceManager.GetString("Order.InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng đang trống..
        /// </summary>
        public static string Order_MustHaveItem {
            get {
                return ResourceManager.GetString("Order.MustHaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn..
        /// </summary>
        public static string Order_NotFound {
            get {
                return ResourceManager.GetString("Order.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn bàn cho đơn dùng tại nhà hàng.
        /// </summary>
        public static string Order_SelectTable {
            get {
                return ResourceManager.GetString("Order.SelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có ít nhất 1 món để gửi bếp.
        /// </summary>
        public static string OrderItem_InvalidQuantity {
            get {
                return ResourceManager.GetString("OrderItem.InvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không khớp..
        /// </summary>
        public static string Password_ConfirmationMismatch {
            get {
                return ResourceManager.GetString("Password.ConfirmationMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại không chính xác..
        /// </summary>
        public static string Password_IncorrectCurrent {
            get {
                return ResourceManager.GetString("Password.IncorrectCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 8 ký tự.
        /// </summary>
        public static string Password_MinLength {
            get {
                return ResourceManager.GetString("Password.MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới phải khác mật khẩu hiện tại..
        /// </summary>
        public static string Password_MustBeDifferent {
            get {
                return ResourceManager.GetString("Password.MustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 số.
        /// </summary>
        public static string Password_RequireDigit {
            get {
                return ResourceManager.GetString("Password.RequireDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 chữ thường.
        /// </summary>
        public static string Password_RequireLowercase {
            get {
                return ResourceManager.GetString("Password.RequireLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 ký tự đặc biệt.
        /// </summary>
        public static string Password_RequireSpecial {
            get {
                return ResourceManager.GetString("Password.RequireSpecial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu phải có ít nhất 1 chữ hoa.
        /// </summary>
        public static string Password_RequireUppercase {
            get {
                return ResourceManager.GetString("Password.RequireUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng bởi người khác..
        /// </summary>
        public static string Profile_EmailExists {
            get {
                return ResourceManager.GetString("Profile.EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng bởi người khác..
        /// </summary>
        public static string Profile_PhoneExists {
            get {
                return ResourceManager.GetString("Profile.PhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeId không được để trống.
        /// </summary>
        public static string ResetPassword_EmployeeIdRequired {
            get {
                return ResourceManager.GetString("ResetPassword.EmployeeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset không được quá 500 ký tự.
        /// </summary>
        public static string ResetPassword_ReasonMaxLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset phải có ít nhất 10 ký tự.
        /// </summary>
        public static string ResetPassword_ReasonMinLength {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do reset password là bắt buộc.
        /// </summary>
        public static string ResetPassword_ReasonRequired {
            get {
                return ResourceManager.GetString("ResetPassword.ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thực hiện thao tác này..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
    }
}
