using FoodHub.Application.Common.Constants;
using FoodHub.Application.Common.Models;
using FoodHub.Application.Constants;
using FoodHub.Application.Interfaces;
using FoodHub.Domain.Entities;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace FoodHub.Application.Features.SetMenus.Commands.CreateSetMenu
{
    public class CreateSetMenuHandler : IRequestHandler<CreateSetMenuCommand, Result<CreateSetMenuResponse>>
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICurrentUserService _currentUserService;
        private readonly IMessageService _messageService;
        private readonly ICacheService _cacheService;
        //private readonly ICloudinaryService _cloudinaryService;

        public CreateSetMenuHandler(IUnitOfWork unitOfWork, ICurrentUserService currentUserService, IMessageService messageService, ICacheService cacheService)//, ICloudinaryService cloudinaryService)
        {
            _unitOfWork = unitOfWork;
            _currentUserService = currentUserService;
            _messageService = messageService;
            _cacheService = cacheService;
            //_cloudinaryService = cloudinaryService;
        }


        public async Task<Result<CreateSetMenuResponse>> Handle(CreateSetMenuCommand request, CancellationToken cancellationToken)
        {
            var setMenuRepository = _unitOfWork.Repository<SetMenu>();
            var menuItemRepository = _unitOfWork.Repository<MenuItem>();
            var categoryRepository = _unitOfWork.Repository<Category>();

            // 1. Check if Category exists
            var category = await categoryRepository.GetByIdAsync(request.CategoryId);
            if (category == null) return Result<CreateSetMenuResponse>.Failure(_messageService.GetMessage(MessageKeys.Category.NotFound, request.CategoryId), ResultErrorType.NotFound);

            // 2. Generate ItemNumber and Code
            var nextItemNumber = await setMenuRepository
                .Query()
                .Where(sm => sm.CategoryId == request.CategoryId)
                .IgnoreQueryFilters()
                .MaxAsync(sm => (int?)sm.ItemNumber) ?? 0;
            nextItemNumber++;

            var autoGeneratedCode = $"{category.CodePrefix}-{nextItemNumber:D2}";

            // 3. Validate if all MenuItems exist
            var menuItemIds = request.Items.Select(i => i.MenuItemId).Distinct().ToList();
            var existingMenuItemsCount = await menuItemRepository.CountAsync(mi => menuItemIds.Contains(mi.MenuItemId));

            if (existingMenuItemsCount != menuItemIds.Count)
            {
                return Result<CreateSetMenuResponse>.Failure(_messageService.GetMessage(MessageKeys.MenuItem.NotFound), ResultErrorType.BadRequest);
            }

            Guid? auditorId = null;
            if (Guid.TryParse(_currentUserService.UserId, out var parsedId))
            {
                auditorId = parsedId;
            }

            // 3. Handle Image Upload if provided
            var imageUrl = request.ImageUrl;
            //if (request.ImageFile != null)
            //{
            //    try
            //    {
            //        imageUrl = await _cloudinaryService.UploadImageAsync(request.ImageFile, "set-menus");
            //    }
            //    catch (Exception ex)
            //    {
            //        return Result<CreateSetMenuResponse>.Failure($"Image upload failed: {ex.Message}", ResultErrorType.BadRequest);
            //    }
            //}

            // 4. Create SetMenu
            var setMenu = new SetMenu
            {
                SetMenuId = Guid.NewGuid(),
                Code = autoGeneratedCode,
                ItemNumber = nextItemNumber,
                CategoryId = request.CategoryId,
                Name = request.Name,
                SetType = request.SetType,
                ImageUrl = imageUrl,
                Description = request.Description,
                Price = request.Price,
                CostPrice = request.CostPrice,
                IsOutOfStock = false,
                CreatedAt = DateTime.UtcNow,
                CreatedBy = auditorId,
                UpdatedBy = auditorId,
                SetMenuItems = request.Items.Select(itemRequest => new SetMenuItem
                {
                    SetMenuItemId = Guid.NewGuid(),
                    MenuItemId = itemRequest.MenuItemId,
                    Quantity = itemRequest.Quantity,
                    CreatedAt = DateTime.UtcNow
                }).ToList()
            };


            // 4. Save to database
            await setMenuRepository.AddAsync(setMenu);
            await _unitOfWork.SaveChangeAsync(cancellationToken);

            await _cacheService.RemoveByPatternAsync("setmenu:list", cancellationToken);

            // 5. Return Response
            var response = new CreateSetMenuResponse
            {
                SetMenuId = setMenu.SetMenuId,
                Code = setMenu.Code,
                Name = setMenu.Name,
                SetType = setMenu.SetType,
                ImageUrl = setMenu.ImageUrl,
                Description = setMenu.Description,
                Price = setMenu.Price,
                CostPrice = setMenu.CostPrice,
                IsOutOfStock = setMenu.IsOutOfStock,
                CreatedAt = setMenu.CreatedAt,
                UpdatedAt = setMenu.UpdatedAt,
                Items = setMenu.SetMenuItems.Select(item => new SetMenuItemResponse
                {
                    SetMenuItemId = item.SetMenuItemId,
                    MenuItemId = item.MenuItemId,
                    Quantity = item.Quantity
                }).ToList()
            };


            return Result<CreateSetMenuResponse>.Success(response);
        }
    }
}
