// <auto-generated />
using System;
using FoodHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FoodHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FoodHub.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delete_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("EmployeeId")
                        .HasName("pk_employees");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_email");

                    b.HasIndex("EmployeeCode")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_employee_code");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_phone");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_employees_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_employees_status");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_username");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("FoodHub.Domain.Entities.PasswordResetLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<Guid>("PerformedByEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by_employee_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("ResetAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reset_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("TargetEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_employee_id");

                    b.HasKey("LogId")
                        .HasName("pk_password_reset_logs");

                    b.HasIndex("PerformedByEmployeeId")
                        .HasDatabaseName("ix_password_reset_logs_performed_by_employee_id");

                    b.HasIndex("ResetAt")
                        .HasDatabaseName("ix_password_reset_logs_reset_at");

                    b.HasIndex("TargetEmployeeId")
                        .HasDatabaseName("ix_password_reset_logs_target_employee_id");

                    b.ToTable("password_reset_logs", (string)null);
                });

            modelBuilder.Entity("FoodHub.Domain.Entities.PasswordResetLog", b =>
                {
                    b.HasOne("FoodHub.Domain.Entities.Employee", "PerformedByEmployee")
                        .WithMany("PerformedLogs")
                        .HasForeignKey("PerformedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_logs_employees_performed_by_employee_id");

                    b.HasOne("FoodHub.Domain.Entities.Employee", "TargetEmployee")
                        .WithMany("TargetLogs")
                        .HasForeignKey("TargetEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_logs_employees_target_employee_id");

                    b.Navigation("PerformedByEmployee");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("FoodHub.Domain.Entities.Employee", b =>
                {
                    b.Navigation("PerformedLogs");

                    b.Navigation("TargetLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
